name: Cherry
version: ${project.version}
main: club.rigox.cherry.Cherry
api-version: 1.16
authors: [ sebastn_chan ]
description: A simple economy plugin with MongoDB
website: https://rigox.club
depend:
  - PlaceholderAPI
  - ScoreboardAPI
